[project]
name = "dot"
version = "0.1.0"
description = "dot files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=13.7.0",
    "furl>=2.1.4",
    "loguru>=0.7.3",
    "openai>=2.33.0",
    "pillow>=12.2.0",
    "python-dotenv>=1.2.2",
    "pywinrm>=0.5.0",
    "requests>=2.33.1",
    "yt-dlp>=2026.3.17",
]
